//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_DetalleFolioPickingTicket
    {
        public int DetalleFolioPickingTicketID { get; set; }
        public int FolioPickingTicketID { get; set; }
        public Nullable<int> OrdenTrabajoMaterialID { get; set; }
        public int DespachoID { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public bool Activo { get; set; }
    
        public virtual Sam3_Despacho Sam3_Despacho { get; set; }
        public virtual Sam3_FolioPickingTicket Sam3_FolioPickingTicket { get; set; }
    }
}
