//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class sam3_sysgo_mrr_pacial
    {
        public string IdentificadorCliente { get; set; }
        public string PODL_SEQNO { get; set; }
        public int id { get; set; }
    }
}
