//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class sam3_sysgo_mrr_franklin
    {
        public Nullable<System.DateTime> TMRR_DATE { get; set; }
        public string TMRR_BJOB_JOBNUMBER { get; set; }
        public string TMRR_SOURCE_APPLICATION { get; set; }
        public string po_number { get; set; }
        public string release_number { get; set; }
        public string podl_seqno { get; set; }
        public string DESTINATION { get; set; }
        public string MRR_Number { get; set; }
        public string ASN_NUMBER { get; set; }
        public Nullable<System.DateTime> TMRR_RECEIPT_DATE { get; set; }
        public Nullable<System.DateTime> TMRR_DOCUMENT_DATE { get; set; }
        public string PL { get; set; }
        public string TMRR_DELIVER_TO { get; set; }
        public string LINENO1 { get; set; }
        public string SUB_LINE1 { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public string TMRR_UOSD_NUMBER { get; set; }
        public string TMRR_UOSD_TYPE { get; set; }
        public Nullable<decimal> TMRR_UOSD_QUANTITY { get; set; }
        public string TMRR_UOSD_REMARKS { get; set; }
        public string TMRR_LOC_ID2 { get; set; }
        public string TMRR_LOC_ID3 { get; set; }
        public string uo { get; set; }
        public string STOCK_CODE { get; set; }
        public string SCTYPE { get; set; }
        public string TMRR_TAGS_ID { get; set; }
        public string TMRR_ENTERED_BY { get; set; }
        public string TMRR_BADGE_ID_CREATE { get; set; }
        public string TMRR_MATERIAL_ID { get; set; }
        public string TMRR_USERSEG_MRR { get; set; }
        public string TMRR_USERSEG_MWR { get; set; }
        public string TMRR_USERSEG_UOSD { get; set; }
        public string SHORT_DESCRIPTION { get; set; }
        public string SCN_NUMBER { get; set; }
    }
}
