//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ItemCode_ICS
    {
        public string Proyecto { get; set; }
        public string Codigo { get; set; }
        public string DescripcionEspanol { get; set; }
        public decimal d1 { get; set; }
        public decimal d2 { get; set; }
        public string codigo_ics { get; set; }
        public string desc_itcs { get; set; }
        public decimal Diametro1 { get; set; }
        public decimal Diametro2 { get; set; }
        public string FamiliaAcero { get; set; }
        public decimal EspesorIn { get; set; }
        public decimal EspesorMM { get; set; }
        public int ItemcodeId { get; set; }
        public string Nombre { get; set; }
    }
}
