//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ResumenNU
    {
        public string Codigo { get; set; }
        public string DescripcionEspanol { get; set; }
        public decimal Diametro1 { get; set; }
        public decimal Diametro2 { get; set; }
        public string Prefijo { get; set; }
        public int Consecutivo { get; set; }
        public int RecibidoCondicionado { get; set; }
        public int RecibidoDanado { get; set; }
        public int RecibidoAprobado { get; set; }
        public int RecibidoEnConteo { get; set; }
        public int DocumentalRechazado { get; set; }
        public int DucumentalAprobado { get; set; }
        public int DocumentalEnConteo { get; set; }
        public int RecibidoAprobadoDocumentalRechazado { get; set; }
        public int RecibidoAprobadoDocumentalAprobado { get; set; }
        public int ProyectoID { get; set; }
        public int NumeroUnicoID { get; set; }
        public int InventarioCongelado { get; set; }
        public int InventarioDisponibleCruce { get; set; }
        public string NU { get; set; }
        public int CantidadDespachada { get; set; }
        public int FisicoCondicionado { get; set; }
        public int FisicoDanado { get; set; }
        public int FisicoAprobado { get; set; }
        public string NumeroColada { get; set; }
        public string NumeroMTR { get; set; }
        public string Factura { get; set; }
        public string fabricante { get; set; }
        public int NumeroUnicoS2 { get; set; }
        public string IdentificadorCliente { get; set; }
        public string NumeroUnicoCliente { get; set; }
        public string Rack { get; set; }
        public string Proveedor { get; set; }
        public string PLCliente { get; set; }
        public int CtdCorte { get; set; }
        public int TotMerma { get; set; }
        public int TipoMaterialID { get; set; }
        public int TotOtrasSalidas { get; set; }
        public string OrdenCompra { get; set; }
        public string foliio { get; set; }
    }
}
